# Base image with Python
FROM python:3.12.8

# Set the working directory
WORKDIR /streamlit_app

COPY . .

# Install the required dependencies
RUN pip install --no-cache-dir -r requirements.txt 
# Expose port 8501 for Streamlit
EXPOSE 8501

# Command to run the app
CMD ["streamlit", "run", "main.py"]

ENTRYPOINT ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]